### ISSUE TITLE
feat: replacing strings

### ISSUE THREAD

**Issue by kosukeKK** [drodil/backstage-plugin-toolbox#110]
Hi, i think it would be cool to have a replacing string tool.

**Comment by kosukeKK** [comment]
Could i implement this?

**Comment by drodil** [comment]
Sure, contributions are more than welcome! Maybe try to think if you can add some other functionality in the tool as well or if it could be merged with the `StringAnalyzer`. Good example here: https://appdevtools.com/string-utilities

**Comment by kosukeKK** [comment]
> add some other functionality in the tool as well 

what do you think  about  merging with StringCase?

**Comment by drodil** [comment]
Yeah that could work too, just requires to rename it to String Utilities or something :)

**Comment by kosukeKK** [comment]
Could you review my PR? https://github.com/drodil/backstage-plugin-toolbox/pull/118

**Comment by kosukeKK** [comment]
@drodil Could you review my PR? https://github.com/drodil/backstage-plugin-toolbox/pull/118
