### ISSUE TITLE
feat: add support for internationalization

### ISSUE THREAD

**Issue by gabrielcbe** [drodil/backstage-plugin-toolbox#122]
I’d like to suggest adding support for internationalization as described in the [Backstage docs](https://backstage.io/docs/plugins/internationalization/).

Backstage itself has already started adding some support in the [user-settings plugin](https://github.com/backstage/backstage/tree/master/plugins/user-settings).

If this is not something you would consider doing but are willing to accept a PR for, I (or someone on my team) may be able to work on it.

Also, would you consider adding a way to show or hide some of the tools for people who might want fewer tools to be accessible/displayed? I am thinking through the permission framework or simply by accepting a prop with the tool’s ID to hide it.

ps: thanks for the amazing plugin.

**Comment by gabrielcbe** [comment]
Thanks a lot! I’ll put a task on my board and submit a PR for the translations as soon as I can.

As for the filter, I think it’s the best way to do it too, but if it takes too much time, a simple array with IDs could work too. I actually found a similar situation while customizing the catalog today. The EntityKindPicker (exported from @backstage/plugin-catalog-react) accepts a prop ‘allowedKinds’ of type string[] to filter the kinds that are displayed in the dropdown.

**Comment by drodil** [comment]
Actually, there is already the possibility to set the tools for the ToolsPage in the `tools` array here https://github.com/drodil/backstage-plugin-toolbox/blob/main/plugins/toolbox/src/components/Root/ToolsPage.tsx#L53.

It will only show the tools passed to that and the defaults are listed here: https://github.com/drodil/backstage-plugin-toolbox/blob/main/plugins/toolbox/src/components/Root/tools.tsx#L51

**Comment by gabrielcbe** [comment]
Thanks a lot for the great and fast work! I pulled the latest version of the toolbox, checked the filter, and it works great.

I’ve started working on the translation: https://github.com/gabrielcbe/backstage-plugin-toolbox/blob/feat/add-translation-for-toolbox/plugins/toolbox/src/translation.ts

When I finish, I’ll make a PR, and we can see if the organization and names I’m pushing will be alright.

I ran into an issue and didn’t find documentation for it. When I need to use the translations outside a React component (e.g., translating the defaultTools), I saw someone making a function that receives the translation function coming from the useTranslationRef hook and using it to return the values…

This way, defaultTools could become a function:

 ```ts
 function getDefaultTools (
  t: TranslationFunction<typeof scaffolderTranslationRef.T>,
): ButtonGroup[] {
  return [
    {
    id: 'base64-encode',
    name: t('tool.base64.name'),
    component: <Base64Encode />,
    category:  t('tool.base64.category),
    description: t('tool.base64.description),
  },
  ]
 ```

or

other possible solution would be to the exported defaultTools, map and translate in my backstage instance and then pass it as a prop.

which seems hacky either way...

 can you think of a better way to implement this?

**Comment by drodil** [comment]
Hi, how about using the translate in the react components but just pass the tool id there something like:

```tsx
t(`tool.${tool.id}.name`)
```

Not sure that works though, would have to test it. Does the translate function have some fallback or other options? That way you could pass the original name there. I am not familiar with; will have a look tomorrow definitely!

**Comment by drodil** [comment]
Hey, found this: https://www.i18next.com/translation-function/essentials

It seems it actually supports fallback so it's not necessary to move the existing names and descriptions to translations. WDYT?

**Comment by gabrielcbe** [comment]
I’m finished for today and have committed a version without the defaultTools translation.

Other than that, I have a few things to define:

1 - Should we translate categories too? It would be nice but might have implications when selecting things or in conditional expressions. We need to check.

2- The DefaultEditor maps over the modes and uses them as labels for the buttons. I haven’t translated them yet. Tomorrow, I’ll translate and see if the changes affect usability in any way. I might have to change some of the conditions related inside some useEffects, like in StringUtilities, but it looks doable.

The
```ts
t(`tool.${tool.id}.name`)
```

seems to be feasible. I can try to test it tomorrow too, and can also apply that to descriptions (and possibly categories).

i18next does seem to support fallback, but the backstage implementations don’t (that I could find). It seems they only implemented the interpolation as BaseOptions. It would be nice to have added the defaultValue.

Internationalization is still marked as experimental, so maybe this is something to suggest to them. Also, a function outside the hook that only returns a string would also solve the defaultTools translation problem.

I didn’t keep a clean commit history and used conventional commits, so I’ll change that tomorrow and submit a PR as a draft so we can discuss there. Or is it best to discuss things here?

**Comment by drodil** [comment]
Oh that's a shame as it uses the i18next underneath https://github.com/backstage/backstage/blob/f51d611d0cdaa7f0fb40605f069023512445198c/packages/core-app-api/src/apis/implementations/TranslationApi/I18nextTranslationApi.ts#L141

Maybe something to ask as a feature to the TranslationAPI in upstream?

**Comment by gabrielcbe** [comment]
For sure something we could ask for upstream, as it would benefit everyone doing.

maybe even some Quality of Life features like:

having the toolboxTranslationRef message type to be a partial, since if after the initial translation, if the toolboxTranslationRef changes, it would break for people using it until every translation required is added to the translated object.

and a way to [extract translations](https://www.i18next.com/how-to/extracting-translations).

Either way I'll find a way to work around this for today and submit my Initial PR, and if they add something like this Upstream we can change it.

**Comment by drodil** [comment]
I actually played a bit with the translations and added support for my Q&A plugin. I discovered that the translations in fact can be partial and updated the upstream documentation here: https://backstage.io/docs/plugins/internationalization/#for-an-application-developer-overwrite-plugin-messages (https://github.com/backstage/backstage/pull/26119)

But extracting them etc. is another thing that should come from upstream. Also did some more work here:
- https://github.com/backstage/backstage/pull/26127
- https://github.com/backstage/backstage/issues/26122

**Comment by gabrielcbe** [comment]
from what I tested so far, i could use t(`tool.${tool.id}.name`)
![image](https://github.com/user-attachments/assets/02871da1-1dc5-46ab-8d96-22b89dc81de2)

but only if I made the id's in the Tool type a exaustive union type of possible Tools ids.
![image](https://github.com/user-attachments/assets/822c8f66-30db-4b5f-8323-8bcf6e738c25)

otherwise i get this error:
![image](https://github.com/user-attachments/assets/133cfc69-c96d-4c30-96d2-1b8f71ccb46d)

Any suggestions?

**Comment by gabrielcbe** [comment]
I did the next best thing I could, I had a custom hook (i18n_UNSAFE) that had a less strict type of string, for input and accepts a fallback.

PR is open, let me know if you want me to change anything before merging

**Comment by drodil** [comment]
How about this: https://www.i18next.com/translation-function/essentials#multiple-fallback-keys
