### ISSUE TITLE
feat: UUID v4 and v7 Generator

### ISSUE THREAD

**Issue by darel-bunnings** [drodil/backstage-plugin-toolbox#126]
Something quick which can be useful while development and testing is generating UUID.

If the toolbox can generate up to 10 (count to be provided by user - default 1), the developers can use it while creating test data or executing manual tests.

**Comment by drodil** [comment]
Ain't there support for this in the Lorem Ipsum tool?

**Comment by darel-bunnings** [comment]
Closing this as this is available under /toolbox#lorem-ipsum-generate
