### ISSUE TITLE
Bug Report: Type 'Tool' is not exported

### ISSUE THREAD

**Issue by gaurav517** [drodil/backstage-plugin-toolbox#20]
Type 'Tool' is not exported in backstage-plugin-toolbox plugin. Type can help a user add a new tool. (We can ignore the error with // @ts-ignore but thats not expected.
```
TS2459: Module '"@drodil/backstage-plugin-toolbox"' declares 'Tool' locally, but it is not exported.
```

**Comment by drodil** [comment]
True. Luckily it's easy to fix, I will take a look tomorrow
