### ISSUE TITLE
Feature Request: Consider exposing components that can be used in a custom tool

### ISSUE THREAD

**Issue by gaurav517** [drodil/backstage-plugin-toolbox#21]
Some components (e.g. `DefaultEditor` and buttons etc.) would be handy in building a custom tool. Please consider exporting them so that they can be used in custom tooling for a consistent look.
For now, we will have to do lot of copying, which is not idea.

**Comment by drodil** [comment]
Great point. I will check this together with fix for exporting the Tool

**Comment by drodil** [comment]
Will release a new version with the fix

**Comment by gaurav517** [comment]
Thats a lot for quick change. :)
