### ISSUE TITLE
CSS issue in the container

### ISSUE THREAD

**Issue by antoniobergas** [drodil/backstage-plugin-toolbox#22]
Hi! I'm testing your plugin for Backstage and I have and issue with the container of the tools.

In theory should be on top of the page near the tools sidebar but I have it always at the very bottom after the sidebar of the tools.

![image](https://user-images.githubusercontent.com/26031467/221157238-ebe62c1d-8bad-49c3-8824-264bf3efee7c.png)

Looks like some css property not working good. I played around with the flex-wrap property to non-wrap in the browser and It looks like the issue gones after that change but not really sure if that its the problem.

![image](https://user-images.githubusercontent.com/26031467/221157810-b637da6d-d1a2-4aba-aeb6-ee62326fae5c.png)

This only happens to me when full screen (1920x1080 right now) if you make smaller the browser the issue not appears

Can you please try to see if you can reproduce it? I will love to have your plugin showing correctly and use it , thank you so much!

**Comment by drodil** [comment]
Thanks for the bug report, I will take a look at this at some point!

**Comment by antoniobergas** [comment]
thanks a lot! I will try it :)
