### ISSUE TITLE
feat: YAML Diff

### ISSUE THREAD

**Issue by aaronnickovich** [drodil/backstage-plugin-toolbox#36]
Tool that compares two YAML text and shows the diff

**Comment by aaronnickovich** [comment]
<img width="1692" alt="screenshot" src="https://user-images.githubusercontent.com/23493031/233483869-dc53821a-3073-4664-9c19-a97ec55ea46f.png">

**Comment by drodil** [comment]
General diff functionality would be nice too, not just for YAMLs :)

**Comment by aaronnickovich** [comment]
@drodil good idea! I'll see if I can make it generic :)

**Comment by aaronnickovich** [comment]
PR to solve this issue: #40
