### ISSUE TITLE
bug: build fails in Backstage app

### ISSUE THREAD

**Issue by drodil** [drodil/backstage-plugin-toolbox#39]
Build fails when adding the 1.9.1 version to backstage app:

`ERROR: Big integer literals are not available in the configured target environment ("es2019")`

This is due to dependency of `ip-num` using bit integers.

**Comment by gbovegra** [comment]
Same error here in @drodil/backstage-plugin-toolbox 1.24.1

**Comment by drodil** [comment]
Which backstage version are you using?

**Comment by gbovegra** [comment]
I am in backstage "version": "1.28.4"

**Comment by drodil** [comment]
You should probably update to 1.30.0+, see https://github.com/backstage/backstage/pull/25738

**Comment by gbovegra** [comment]
Yes, it seems to solve it. Thanks!
