### ISSUE TITLE
feat: timer alert

### ISSUE THREAD

**Issue by efenner-cambia** [drodil/backstage-plugin-toolbox#41]
I would like to have some kind of chime or alert when the countdown timer reaches 0:00:00. Without an alert when it is done, the utility is significantly reduced.

Is this possible already? If so, it would be great to surface the relevant documentation

**Comment by drodil** [comment]
This feature doesn't exist yet but it's a good idea. I think user could even select visual or audible alert when the time runs out. If you have time and skillset, feel free to contribute!

**Comment by efenner-cambia** [comment]
I don't think I have the relevant skillset to implement myself, but I would be happy to support and provide review/feedback if someone else is able to.

**Comment by efenner-cambia** [comment]
Ok, I was messing around with it as a custom tool and got a chime working after some sleuthing. I will create a PR!

**Comment by efenner-cambia** [comment]
Created: https://github.com/drodil/backstage-plugin-toolbox/pull/42
