### ISSUE TITLE
CSP error loading File Diff tool

### ISSUE THREAD

**Issue by tsoslow** [drodil/backstage-plugin-toolbox#49]
When accessing the File Diff tool, we are getting a CSP error trying to access monaco-editor js.

Refused to load the script 'https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/loader.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Maybe monaco-editor could be hosted locally rather than going to cdn?

**Comment by drodil** [comment]
Yeah it absolutely should be hosted locally or bundled to the plugin. One of the basic principles of the plugin is to provide all necessary things without leaking data to internet.

**Comment by ppiwow-apay** [comment]
any planned work here?

**Comment by drodil** [comment]
@aaronnickovich  any chance you could have a look at this?

**Comment by ppiwow-apay** [comment]
any updates?

**Comment by drodil** [comment]
Did you try with the latest version?

**Comment by ppiwow-apay** [comment]
oh, sorry, just checked and seems to be working fine. thanks
