### ISSUE TITLE
Create new release to add new tool

### ISSUE THREAD

**Issue by tanoggy** [drodil/backstage-plugin-toolbox#52]
Pull request is merged https://github.com/drodil/backstage-plugin-toolbox/pull/50 but not ready to use, please create new release

**Comment by tanoggy** [comment]
@dweber019 make feature ready to use, many thanks

**Comment by tanoggy** [comment]
sr @dweber019, hi @drodil please help me

**Comment by drodil** [comment]
Yeah sure,  I will create release!

**Comment by tanoggy** [comment]
> Yeah sure, I will create release!

https://github.com/drodil/backstage-plugin-toolbox/actions/runs/5949990219
fix the pipeline to release on npm
