### ISSUE TITLE
QR code generator fails for more than 23648 characters

### ISSUE THREAD

**Issue by floric** [drodil/backstage-plugin-toolbox#67]
Hey :)

by accident we found out, that the QR code generator throws an error for contents with more than 23648 characters.
Of course this is no valid usecase. But maybe a nice more user friendly error message could be shown instead of:

```
Error
Error

Message
code length overflow. (23780>23648)

Stack Trace
Error: code length overflow. (23780>23648)
```

**Comment by drodil** [comment]
Not really a real use case, true, but makes sense to validate the input and show better error. Or even cut the maximum characters in the input field. 

Would you be willing to provide a PR or should I look at this when I have time? Thanks for the report!

**Comment by floric** [comment]
> Not really a real use case, true, but makes sense to validate the input and show better error. Or even cut the maximum characters in the input field.
> 
> Would you be willing to provide a PR or should I look at this when I have time? Thanks for the report!

Hey :) An MR should be possible. I will have a look.

**Comment by floric** [comment]
Oh, thanks Heikki for already solving it.
