### ISSUE TITLE
Searching "JWT" should return the "JSON Web Token" tool

### ISSUE THREAD

**Issue by bforbis** [drodil/backstage-plugin-toolbox#77]
**Description**

I realize the search is very basic here, but it is very idiomatic to call "JSON Web Tokens" JWTs, so it would be good if this tool showed up when a user types in that search term.

Example: Search on "Token". Finds the tool.
![image](https://github.com/drodil/backstage-plugin-toolbox/assets/16994570/bb2ed95f-834c-43e0-a528-a57454e1070c)

Example: Search on "jwt". Does not find the tool.
![image](https://github.com/drodil/backstage-plugin-toolbox/assets/16994570/f8f8db30-3636-48b8-ae4f-e420be102f8e)

**Comment by drodil** [comment]
Thanks for this, will create some improvement for the search!
