### ISSUE TITLE
Suggestion: Recommend CardTravel MUI4 icon in installation docs

### ISSUE THREAD

**Issue by bforbis** [drodil/backstage-plugin-toolbox#78]
The `CardTravel` icon from https://v4.mui.com/components/material-icons/ looks kind of like a toolbox (I think it's actually a credit card with a handle, which is kind of odd??).

<img width="135" alt="image" src="https://github.com/drodil/backstage-plugin-toolbox/assets/16994570/763a6674-1416-44ce-a38a-d56551f19e16">

I chose to use this in my installation because I'm already using the [DevTools plugin](https://github.com/backstage/backstage/tree/master/plugins/devtools) which already makes use of the `Build` MUI4 icon and didn't want users to get confused.

```
import CardTravel from '@material-ui/icons/CardTravel';
```

As an aside note, I kind of wish the devtools plugin was just extra tabs under user settings to not overload the sidebar with another icon, but that's a separate issue entirely.

**Comment by drodil** [comment]
Sure thing, could you make a PR to update the docs and recommend that icon? Makes more sense. Also it should be possible to add the toolbox to user settings by just using the `ToolsPage` as tab content.
