### ISSUE TITLE
Question: plan for moving to mui v5?

### ISSUE THREAD

**Issue by JGoggers** [drodil/backstage-plugin-toolbox#88]
Hello, 

As I see it, the toolbox is on mui v4. Do you have any plans on moving to mui v5 or accomodating it? 

I ask as we run into some styling issues as most of our application is on mui v5 and the necessary overrides we have in place affect the styling in the toolbox.  

(Also open to creating a PR)

Thanks!

**Comment by drodil** [comment]
Yeah, there is plan to migrate to MUIv5 but lack of time has been the main reason not doing this yet. If you instead have some time, I would really appreciate contributions ❤️

**Comment by JGoggers** [comment]
Great, I'll make a PR for it then 😄
