### ISSUE TITLE
feat: QR code generator

### ISSUE THREAD

**Issue by drodil** [drodil/backstage-plugin-toolbox#9]
Tool that generates QR code based on the input. QR code types that at least should be supported are URL, VCARD, Email, Event, Geo coordinate, Plain text, SMS, Telephone and WiFi. Additionally allow user to select the amount of error correction for the generated code.

**Comment by tanoggy** [comment]
[Featre](https://github.com/drodil/backstage-plugin-toolbox/pull/50)

**Comment by tanoggy** [comment]
https://github.com/drodil/backstage-plugin-toolbox/pull/50
