### ISSUE TITLE
Feature: JSON to typescript generator

### ISSUE THREAD

**Issue by dariozachow** [drodil/backstage-plugin-toolbox#93]
Something similar to https://quicktype.io/typescript would be awesome to generate types from given json

**Comment by drodil** [comment]
Good idea, and why not support all the other languages quicktype supports. The tool could be called `Type generator` or something. It should be quite straightforward to implement, see here: https://github.com/glideapps/quicktype?tab=readme-ov-file#calling-quicktype-from-javascript

Any chance you would like to come up with a PR? I might have some time at some point to look at this but contributions are always more than welcome :)

**Comment by dariozachow** [comment]
Hey, thanks for your quick answer. I think supporting all languages is a good idea, typescript just came first to my mind.

I'm definitely open to contribute to this project but need to plan it for my next sprint. Just need to clarify some things with my team which means I'll probably open the PR next week.
